spring.datasource.url=jdbc:mysql://localhost:3306/payment_simulator?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=harshraj_dev
spring.datasource.password=harshraj_dev
spring.jpa.hibernate.ddl-auto=update