spring.datasource.url=jdbc:h2:mem:payment_simulator
spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=harshraj
spring.datasource.password=harshraj

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console